// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Session struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	RefreshToken string       `json:"refresh_token"`
	IsUsed       sql.NullBool `json:"is_used"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
}
