// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
